# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeModels', to='search.Make')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=150)),
                ('hp', models.CharField(max_length=9)),
                ('tq', models.CharField(max_length=9)),
                ('fuelEco', models.CharField(max_length=9)),
                ('weight', models.CharField(max_length=9)),
                ('drivetrain', models.CharField(max_length=9)),
                ('transmission', models.CharField(max_length=50)),
                ('msrp', models.CharField(max_length=9)),
				('url', models.CharField(max_length=250)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeTrims', to='search.Make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelTrims', to='search.Model')),
            ],
        ),
    ]
