# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trim',
            old_name='hp',
            new_name='horsepower',
        ),
        migrations.RenameField(
            model_name='trim',
            old_name='tq',
            new_name='torque',
        ),
    ]
