# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160605_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='make',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='make',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='model',
        ),
        migrations.DeleteModel(
            name='Make',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Trim',
        ),
    ]
